# Generated by Django 5.0.6 on 2025-05-15 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil_composition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilsoter',
            name='site',
        ),
        migrations.DeleteModel(
            name='SoilParams',
        ),
        migrations.DeleteModel(
            name='SoilSoter',
        ),
        migrations.DeleteModel(
            name='SoilUnit',
        ),
    ]
