# Generated by Django 5.0.6 on 2025-05-14 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_remove_farmerprofile_subscription_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=10, unique=True)),
                ('stripe_price_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.farmerprofile')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscriptionplan')),
            ],
        ),
    ]
