# Generated by Django 5.0.6 on 2025-05-07 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cropfield_croptask_fertilizer_material_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
