# Generated by Django 5.0.6 on 2025-05-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_fertilizer_date_alter_material_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
