# Generated by Django 5.0.6 on 2025-05-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_farmerprofile_subscription_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='subscription_start',
        ),
    ]
