# Generated by Django 5.0.6 on 2025-05-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rainfall_forcasting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RainfallPrediction',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
